sudo: false
language: python
python:
  - 3.6
install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis
  - pip install codecov
script:
  - tox
after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION

